pinches/urls.py
from django.conf.urls import url
from pinches.views import NewPinchView, PinchListView
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', NewPinchView.as_view(), name='new_pinch'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^done/$', PinchListView.as_view(are_done=True), name='done_list'),
    url(r'^pending/$', PinchListView.as_view(are_done=False), name='pending_list'),

]

youpinch/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'youpinch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('pinches.urls', namespace='pinches')),
]

pinches/models.py
from django.db import models


class Pinch(models.Model):
    """
    Simple class for pinches
    """
    artist = models.CharField(max_length=256)
    song = models.CharField(max_length=256)
    link = models.URLField(max_length=256, unique=True)
    is_done = models.BooleanField(default=False)

pinches/forms.py
from django.forms import ModelForm, ValidationError
from pinches.models import Pinch
from pinches.utils import thread_it, yt_dl, store_it
from django.core.exceptions import PermissionDenied, ImproperlyConfigured


class PinchModelForm(ModelForm):
    """
    Simple form for a Pinch
    """

    @thread_it
    def pinch_it(self, artist, song, link):
        exit_download = yt_dl(song, link)
        if exit_download == 0:
            exit_store = store_it(artist, song)
            if exit_store == 0:
                pinch = Pinch.objects.get(link=link)
                pinch.is_done = True
                pinch.save()
            else:
                raise PermissionDenied()
        else:
            raise ImproperlyConfigured()

    class Meta:
        model = Pinch
        fields = ['artist', 'song', 'link']
        labels = {
            'artist': ('Artist'),
            'song': ('Song'),
            'link': ('Youtube link')
        }
        help_text = {
            'artist': ('Ej.: Todo o Nada'),
            'song': ('Ej.: Sin mirar'),
            'link': ('Ej.: https://www.youtube.com/watch?v=dnoqifJ3UV0')
        }

    def clean(self):
        if Pinch.objects.filter(is_done=False).count() > 9:
            raise ValidationError("Demasiadas descargas juntas! Esperemos un poco!")

pinches/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from pinches.forms import PinchModelForm
from pinches.models import Pinch
from pinches.utils import escape


def index(request):
    return render(request, 'pinches/index.html')


def thanks(request):
    return render(request, 'pinches/thanks.html')


class PinchListView(ListView):

    are_done = True

    context_object_name = 'pinches'
    template_name = 'pinches/list.html'

    def get_queryset(self):
        return Pinch.objects.filter(is_done=self.are_done)


class NewPinchView(CreateView):
    template_name = 'pinches/new.html'
    form_class = PinchModelForm
    success_url = '/thanks/'
    model = Pinch

    def form_valid(self, form):
        form.pinch_it(escape(form.cleaned_data['artist']),
                      escape(form.cleaned_data['song']),
                      escape(form.cleaned_data['link']))

        return super(NewPinchView, self).form_valid(form)

pinches/templates/pinches/index.html
{% extends "foundation/base.html" %}

{% block base_body %}
<div class="row">
    <div class="large-12 columns">
        <h1>YouPinch!</h1>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h3>Reconstruyamos Alexandria!</h3>
            <br>
                <p>Esta es una herramienta libre pensada para facilitar la descarga de música en la colonia!</p>
                <p>Una vez acabada la descarga podrás encontrar la musica en omnius: accede a través de un cliente como Filezilla o navega con el navegador a <a href="ftp://omnius.calafou/MEDIATECA/audio/music/">Mediateca</a></p>
                <center><a href="{% url 'pinches:new_pinch' %}" class="medium alert radius button">Pinch it!</a></center>
        </div>
    </div>
</div>
{% endblock %}

pinches/templates/pinches/list.html
{% extends "foundation/base.html" %}

{% block base_body %}
<div class="row">
    <div class="large-12 columns">
        <h1>YouPinch!</h1>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h3>Que crezca!</h3>
            {% if pinches %}
            <ul>
                {% for pinch in pinches %}
                <li>{{ pinch.song }} - {{ pinch.artist }}</li>
                {% endfor %}
            </ul>
            {% else %}
            <p> No hay descargas </p>
            {% endif %}
        </div>
    </div>
</div>
<div class="row">
    <div class="small-3 small-centered columns">
        <a href="{% url 'pinches:index' %}" class="medium alert radius button">Pinch!</a>
    </div>
</div>
{% endblock %}

pinches/templates/pinches/new.html
{% extends "foundation/base.html" %}

{% block base_body %}
<div class="row">
    <div class="large-12 columns">
        <h1>YouPinch!</h1>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h3>Pinch It!</h3>
                <p>Intenta ser cuidadosa con los datos que introduces:</p>
                <p>El nombre del artista se convertira en el nombre de la carpeta en el servidor</p>
                <p>El nombre de la canción será el nombre del archivo adentro de la carpeta</p>
                <p>Procura copiar el enlace de yt entero incluyendo "https://"</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <form action="" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
                <div class="row">
                    <div class="large-6 medium-6 columns">
                    {{ form.artist.errors }}
                    {{ form.artist.label_tag }}
                    {{ form.artist }}
                    </div>
                    <div class="large-6 medium-6 columns">
                    {{ form.song.errors }}
                    {{ form.song.label_tag }}
                    {{ form.song }}
                    </div>
                </div>
                <div class"row">
                    <div class="large-8 large-centered columns">
                    {{ form.link.errors }}
                    {{ form.link.label_tag }}
                    {{ form.link }}
                    </div>
                </div>
                <div class="row">
                    <div class="small-10 columns">
                    </div>
                    <div class="small-2 columns">
                    <input class="medium success radius button" type="submit" value="Pinch it!" />
                    </div>   
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pinches/templates/pinches/thanks.html
{% extends "foundation/base.html" %}

{% block base_body %}
<div class="row">
    <div class="large-12 columns">
       <h1>YouPinch!</h1>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h3>Gracias por compartir!</h3>
            <br>
                <p>Tu descarga se esta procesando!</p>
                <p>Estas curiosa?</p>
                <div class="row">
                    <div class="large-3 medium-3 columns">
                    </div>
                    <div class="large-3 medium-3 columns">
                        <a href="{% url 'pinches:pending_list' %}" class="small info radius button">Descargas en curso</a>
                    </div>
                    <div class="large-3 medium-3 columns">
                        <a href="{% url 'pinches:done_list' %}" class="small info radius button">Ultimas descargadas</a>
                    </div>
                    <div class="large-3 medium-3 columns">
                        <a href="{% url 'pinches:index' %}" class="small alert radius button">Bienvenida!</a>
                    </div>
                </div>
        </div>
    </div>
</div>
{% endblock %}